dataset:
  repo_id: "/home/yang/TactileEncoder/dataset/so101/eval_act_350_slow_805_clean"
  root: null
  revision: null
  video_backend: "torchcodec"

  keys:
    tactile_type: "force"

    # 历史力数据（VQ-VAE编码器输入）
    tactile_force:
      - "observation.tactile.left_force"
      - "observation.tactile.right_force"

    # 当前力数据（CurrentForceEncoder输入）
    current_force:
      - "observation.tactile.left_force"
      - "observation.tactile.right_force"

    # 机器人状态（StateEncoder输入）
    state: "observation.state"

    # 专家动作（目标输出）
    expert_action: "action"

  # ACT策略使用的观测字段
  act_observation_keys:
    - "observation.state"
    # - "observation.images.realsense"
    # - "observation.images.wrist_cam"

sequence:
  tactile_history_force: 30  # 历史力时间步数
  action_horizon: 30         # 动作预测时间步数

policy:
  type: "act"
  pretrained_path: "/home/yang/TactileEncoder/actmodel/dm_act_orin_fail/so101/dm_act_orin_fail/checkpoints/100000"
  revision: null
  device: "cuda"
  use_postprocessor: true

split:
  train: 0.70
  val: 0.15
  test: 0.15
  seed: 42

loader:
  batch_size: 16
  num_workers: 4
  pin_memory: true
  persistent_workers: true
  shuffle_train: true
  drop_last_train: false

test:
  num_batches: 2
